version: "3"
services:
  redis:
    container_name: redis
    image: redis
  web:
    container_name: pamw_app
    restart: always
    build: ./pamw-flask
    command: []
    ports:
      - "3000:80"
    environment:
      - REDIS_NAME=redis
    depends_on:
      - redis
  webserv:
    container_name: pamw_rest
    restart: always
    build: ./pamw-serwer
    command: []
    ports:
      - "5000:81"